# Generated by Django 4.1 on 2022-08-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_rename_person_vehicle_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cpf',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.IntegerField(choices=[(1, 'Yellow'), (2, 'Blue'), (3, 'Gray')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.IntegerField(choices=[(1, 'Hatch'), (2, 'Sedan'), (3, 'Convertible')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(max_length=12),
        ),
    ]
