# Generated by Django 4.1 on 2022-08-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_customer_cpf_alter_vehicle_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sales_oportunity',
            field=models.BooleanField(default=False),
        ),
    ]
