# Generated by Django 4.1 on 2022-08-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_rename_sales_oportunity_customer_is_sales_oportunity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='plate',
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_sales_oportunity',
            field=models.BooleanField(default=True),
        ),
    ]
