# Generated by Django 4.1 on 2022-08-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_remove_vehicle_plate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cpf',
        ),
        migrations.AddField(
            model_name='customer',
            name='social_security_number',
            field=models.CharField(default='', max_length=9),
        ),
    ]
