# Generated by Django 4.1 on 2022-08-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_remove_customer_cpf_customer_social_security_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_sales_oportunity',
        ),
        migrations.AlterField(
            model_name='customer',
            name='social_security_number',
            field=models.CharField(max_length=9, unique='True'),
        ),
    ]
